# Generated by Django 4.1.9 on 2023-05-21 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendShip",
        ),
    ]
